In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_parquet("../../data/EDA - SALES DATA/Sales/merged_data.parquet")

In [3]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,None,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,None,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,None,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,29.99,7.78,1.0,credit_card,3.0,37.77,b46f1e34512b0f4c74a72398b03ca788,4.0,None,Deveriam embalar melhor o produto. A caixa vei...,2017-08-19 00:00:00,2017-08-20 15:16:36,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP,9350.0,maua,SP
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,29.99,7.78,1.0,credit_card,1.0,37.77,dc90f19c2806f1abba9e72ad3c350073,5.0,None,"Só achei ela pequena pra seis xícaras ,mais é ...",2017-08-08 00:00:00,2017-08-08 23:26:23,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP,9350.0,maua,SP

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  payment_sequential             119140 non-null  float64
 15  payment_type                   119140 non-null  object
 16  payment_installments           119140 non-null  float64
 17  payment_value                  119140 non-null  float64
 18  review_id                      118146 non-null  object
 19  review_score                   118146 non-null  float64
 20  review_comment_title           13989 non-null   object
 21  review_comment_message         50245 non-null   object
 22  review_creation_date           118146 non-null  object
 23  review_answer_timestamp        118146 non-null  object
 24  product_category_name          116601 non-null  object
 25  product_name_lenght            116601 non-null  float64
 26  product_description_lenght     116601 non-null  float64
 27  product_photos_qty             116601 non-null  float64
 28  product_weight_g               118290 non-null  float64
 29  product_length_cm              118290 non-null  float64
 30  product_height_cm              118290 non-null  float64
 31  product_width_cm               118290 non-null  float64
 32  customer_unique_id             119143 non-null  object
 33  customer_zip_code_prefix       119143 non-null  int64
 34  customer_city                  119143 non-null  object
 35  customer_state                 119143 non-null  object
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
dtypes: float64(15), int64(1), object(23)
memory usage: 35.5+ MB

In [5]:
null = df.columns[df.isnull().sum()>0].tolist()
null_dict = {i:df[i].isnull().sum() for i in null}
null_dict

{'order_approved_at': 177,
 'order_delivered_carrier_date': 2086,
 'order_delivered_customer_date': 3421,
 'order_item_id': 833,
 'product_id': 833,
 'seller_id': 833,
 'shipping_limit_date': 833,
 'price': 833,
 'freight_value': 833,
 'payment_sequential': 3,
 'payment_type': 3,
 'payment_installments': 3,
 'payment_value': 3,
 'review_id': 997,
 'review_score': 997,
 'review_comment_title': 105154,
 'review_comment_message': 68898,
 'review_creation_date': 997,
 'review_answer_timestamp': 997,
 'product_category_name': 2542,
 'product_name_lenght': 2542,
 'product_description_lenght': 2542,
 'product_photos_qty': 2542,
 'product_weight_g': 853,
 'product_length_cm': 853,
 'product_height_cm': 853,
 'product_width_cm': 853,
 'seller_zip_code_prefix': 833,
 'seller_city': 833,
 'seller_state': 833}

In [6]:
sorted_null = sorted(null_dict.items(), key=lambda x:x[1], reverse=True)
drop_null = [] # drop null values from col if null values is less than 1000 which is 1% of data
for i in range(len(sorted_null)):
    if sorted_null[i][1] < 1000:
        drop_null.append(sorted_null[i][0])
        
drop_null

['review_id',
 'review_score',
 'review_creation_date',
 'review_answer_timestamp',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'seller_zip_code_prefix',
 'seller_city',
 'seller_state',
 'order_approved_at',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value']

In [7]:
df = df.dropna(subset=drop_null, axis=0)

In [8]:
df[df.columns[df.isnull().sum()>0]].isnull().sum()

order_delivered_carrier_date       1235
order_delivered_customer_date      2471
review_comment_title             103402
review_comment_message            67637
product_category_name              1675
product_name_lenght                1675
product_description_lenght         1675
product_photos_qty                 1675
dtype: int64

In [9]:
df.order_delivered_carrier_date = df.order_delivered_carrier_date.fillna(method='ffill', axis=0)

df.order_delivered_customer_date = df.order_delivered_customer_date.fillna(method='ffill', axis=0)

df.review_comment_title = df.review_comment_title.fillna('N/A', axis=0)

df.review_comment_message = df.review_comment_message.fillna('N/A', axis=0)

In [10]:
len(np.where((df.product_category_name.isnull() ==True)&(df.product_name_lenght.isnull() ==True)&(df.product_description_lenght.isnull() ==True)&(df.product_photos_qty.isnull() ==True))[0])

# #all have same common null values
df.loc[df.index[np.where((df.product_category_name.isnull() ==True)&(df.product_name_lenght.isnull() ==True)&(df.product_description_lenght.isnull() ==True)&(df.product_photos_qty.isnull() ==True))[0]]]
# #can't work cuz all values are null

df.product_category_name.value_counts() #no product has been purchased single time wow!
# fas all 4 has same null we should fill them by "null_name"  ->> everything normal just it doesnot have basic name and lenght
df.product_category_name = df.product_category_name.fillna("Null", axis=0)
df.product_name_lenght = df.product_name_lenght.fillna("Null", axis=0)
df.product_description_lenght = df.product_description_lenght.fillna("Null", axis=0)
df.product_photos_qty = df.product_photos_qty.fillna("Null", axis=0)
df.isnull().sum().sum()

0

In [11]:
df.product_category_name.info()

<class 'pandas.core.series.Series'>
Index: 117294 entries, 0 to 119142
Series name: product_category_name
Non-Null Count   Dtype
--------------   -----
117294 non-null  object
dtypes: object(1)
memory usage: 5.8+ MB

In [12]:
df[df.duplicated()==True] # no duplicate

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, payment_sequential, payment_type, payment_installments, payment_value, review_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [13]:
num = df.select_dtypes(exclude='object').columns.tolist()
print(num, '\n')
cat = df.select_dtypes(exclude=['int','float']).columns.tolist()
print(cat)

['order_item_id', 'price', 'freight_value', 'payment_sequential', 'payment_installments', 'payment_value', 'review_score', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'customer_zip_code_prefix', 'seller_zip_code_prefix']

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'product_id', 'seller_id', 'shipping_limit_date', 'payment_type', 'review_id', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'customer_unique_id', 'customer_city', 'customer_state', 'seller_city', 'seller_state']

In [14]:
import json
note = {'num':num, 'cat':cat}
# with open('note.json', 'w') as file:
#     file.write(json.dumps(note))

In [15]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,N/A,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,N/A,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,N/A,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,29.99,7.78,1.0,credit_card,3.0,37.77,b46f1e34512b0f4c74a72398b03ca788,4.0,N/A,Deveriam embalar melhor o produto. A caixa vei...,2017-08-19 00:00:00,2017-08-20 15:16:36,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP,9350.0,maua,SP
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,29.99,7.78,1.0,credit_card,1.0,37.77,dc90f19c2806f1abba9e72ad3c350073,5.0,N/A,"Só achei ela pequena pra seis xícaras ,mais é ...",2017-08-08 00:00:00,2017-08-08 23:26:23,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP,9350.0,maua,SP

In [ ]:
# df.to_csv("../../data/clean_sales_data/clean_sales_data.csv")

# df_p = pd.read_csv("../../data/clean_sales_data/clean_sales_data.csv")

# df_p.to_parquet("../../data/clean_sales_data/clean_sales_data.parquet")